name: trackit_history
description: Trackit logger extension for storing logs events in a memory.
version: 0.1.3
homepage: https://github.com/unger1984/trackit

funding:
  - https://boosty.to/unger1984

topics:
  - cross-platform
  - storage
  - logging
  - logger
  - logs

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  trackit: ^0.1.4

dev_dependencies:
  lints: ^6.1.0
  test: ^1.26.0
