name: trackit_console
description: Trackit logger extension fror formatting and outputting logs to the console. Use this with Dart applications.
version: 0.3.3
homepage: https://github.com/unger1984/trackit

funding:
  - https://boosty.to/unger1984

topics:
  - cross-platform
  - logging
  - logger
  - logs
  - log

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.17.0
  trackit: ^0.1.4

dev_dependencies:
  lints: ^6.1.0
  test: ^1.26.0
